### ISSUE TITLE
Typescript not compiling

### ISSUE THREAD

**Issue by ebisbe** [awboost/cfntypes#1]
Hi,

After adding the tsconfig file I got this error from this package. Any idea what might be happening? `Cannot find module '@awboost/cfntypes' or its corresponding type declarations.ts(2307)`

**Comment by gordonmleigh** [comment]
It's probably related to me getting rid of the default export for the package and switching to sub package imports. You need to set [`moduleResolution`](https://www.typescriptlang.org/tsconfig#moduleResolution) to `nodenext`, `node16` or `bundler` in your own `tsconfig.json`.

I appreciate the support but I'm going to close this issue due to #3. I'd love if you let me know how you found the package and what you're using it for though.
